export const productEditorialContent = {
  'monarch-heritage-silver': {
    hero: {
      enabled: true,
      desktopImage: '',
      mobileImage: '',
      alt: 'Monarch Heritage Silver watch editorial hero',
      focalPoint: 'center',
      theme: 'light',
      motionPreset: 'hero-sequence',
      fallback: 'product-gallery',
    },
    story: {
      enabled: true,
      desktopImage: '/images/editorial/screen.png',
      mobileImage: '/images/editorial/screen.png',
      alt: 'Skeleton watch displayed on a dark stone plinth',
      caption: 'Editorial detail study.',
      focalPoint: '42% 48%',
      eyebrow: 'Monarch Studio',
      heading: 'A quiet dress watch for polished days.',
      body: '',
      imagePosition: 'right',
      theme: 'light',
      motionPreset: 'text-stagger',
      fallback: 'product-content',
    },
    editorialImage: {
      enabled: false,
      desktopImage: '',
      mobileImage: '',
      alt: '',
      caption: '',
      focalPoint: 'center',
      imagePosition: 'center',
      theme: 'light',
      motionPreset: 'image-clip',
      fallback: 'hide',
    },
    craft: {
      enabled: false,
      desktopImage: '',
      mobileImage: '',
      alt: '',
      eyebrow: '',
      heading: '',
      body: '',
      imagePosition: 'left',
      theme: 'light',
      motionPreset: 'image-clip',
      fallback: 'hide',
    },
    signatureMoment: {
      enabled: true,
      desktopImage: '/images/editorial/screen.png',
      mobileImage: '/images/editorial/screen.png',
      alt: 'Skeleton watch displayed on a dark stone plinth',
      eyebrow: '',
      heading: 'A quiet study in detail.',
      body: 'A close view of the watch as texture, shadow, and polished metal become the focus.',
      caption: 'Editorial detail study.',
      focalPoint: '42% 48%',
      theme: 'dark',
      motionPreset: 'subtle-parallax',
      fallback: 'hide',
    },
  },
}

export default productEditorialContent
